name: Download Instagram Files

on: 
  schedule:
    - cron: '0 1 * * *'

jobs:
  download:
    name: Download
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download Instagram
        uses: konstantinkobs/jekyll-instagram-github-action@master
        with:
          account-name: odermalso
          output-path: _data/instagram.yml
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Instagram Photos
